### PR TITLE
Added detection of Recent Apps List swipe away, and send an intent to the runtime.

### PR DESCRIPTION
**Pull request by jhugman**

### CODE REVIEW

**Comment by ozten** [comment]
Awesome! Who can code review?

**Comment by jhugman** [comment]
I've put a reference to this PR in 
https://bugzilla.mozilla.org/show_bug.cgi?id=958709#c9 as part of a r?.

At this edge of two worlds (bugzilla/hg v Github/git) I'm not sure what 
is normal.

**Comment by ozten** [comment]
Perfect!

**Comment by mykmelez** [comment]
@mfinkle, you reviewed the Fennec code for this feature; perhaps you can review the library code too?

**Pull request merged**
